name: recon-demo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # PyTorch and CUDA (compatible with diffusers 0.21.0)
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  
  # Core ML libraries
  - numpy=1.24.3
  - pillow=10.0.0
  
  # HuggingFace ecosystem (versions compatible with diffusers 0.21.0)
  - pip
  - pip:
    - diffusers==0.21.0
    - transformers==4.33.2
    - accelerate==0.21.0
    - safetensors==0.3.3
    - datasets==2.14.4
    
    # Image processing
    - opencv-python==4.8.0.76
    
    # FAISS for similarity search (optional)
    - faiss-cpu==1.7.4
    # Note: Use faiss-gpu instead if you have GPU support
    
    # NLP processing (optional)
    - spacy==3.6.1
    
    # Utilities
    - tqdm==4.66.1
    - requests==2.31.0
    - packaging==23.1
    
    # Development tools (optional)
    - jupyter==1.0.0
    - matplotlib==3.7.2
    - scipy==1.11.2

# Post-install commands for spaCy model (run manually)
# python -m spacy download en_core_web_trf